package com.crx.mapper;

import com.crx.pojo.Cost;
import com.crx.pojo.CostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    long countByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int deleteByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int insert(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int insertSelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    List<Cost> selectByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    Cost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cost record, @Param("example") CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int updateByExample(@Param("record") Cost record, @Param("example") CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int updateByPrimaryKeySelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    int updateByPrimaryKey(Cost record);
}