package com.sys.pojo;

import java.util.Date;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.title
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.time
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.author
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    private String author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.title
     *
     * @return the value of file.title
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.title
     *
     * @param title the value for file.title
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.time
     *
     * @return the value of file.time
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.time
     *
     * @param time the value for file.time
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.author
     *
     * @return the value of file.author
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.author
     *
     * @param author the value for file.author
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author;
    }
}