package com.sys.pojo;

public class PerforationNotice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perforation_notice.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perforation_notice.rw_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer rwId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perforation_notice.wi_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer wiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perforation_notice.demo
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String demo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perforation_notice.id
	 * @return  the value of perforation_notice.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perforation_notice.id
	 * @param id  the value for perforation_notice.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perforation_notice.rw_id
	 * @return  the value of perforation_notice.rw_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getRwId() {
		return rwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perforation_notice.rw_id
	 * @param rwId  the value for perforation_notice.rw_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setRwId(Integer rwId) {
		this.rwId = rwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perforation_notice.wi_id
	 * @return  the value of perforation_notice.wi_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getWiId() {
		return wiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perforation_notice.wi_id
	 * @param wiId  the value for perforation_notice.wi_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setWiId(Integer wiId) {
		this.wiId = wiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perforation_notice.demo
	 * @return  the value of perforation_notice.demo
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getDemo() {
		return demo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perforation_notice.demo
	 * @param demo  the value for perforation_notice.demo
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setDemo(String demo) {
		this.demo = demo;
	}
}