package com.sys.pojo;


public class Roadwork {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.layer_place
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String layerPlace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.layer_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer layerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.hole_way
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String holeWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.perforation_way
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String perforationWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.perforation_well_section
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String perforationWellSection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.perforation_thick
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double perforationThick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.hole_density
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double holeDensity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.hole_count
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer holeCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.bullet_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String bulletType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.deep_all
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double deepAll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.hole_all
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer holeAll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roadwork.gun_bullet_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String gunBulletType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.id
	 * @return  the value of roadwork.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.id
	 * @param id  the value for roadwork.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.layer_place
	 * @return  the value of roadwork.layer_place
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getLayerPlace() {
		return layerPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.layer_place
	 * @param layerPlace  the value for roadwork.layer_place
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setLayerPlace(String layerPlace) {
		this.layerPlace = layerPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.layer_id
	 * @return  the value of roadwork.layer_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getLayerId() {
		return layerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.layer_id
	 * @param layerId  the value for roadwork.layer_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setLayerId(Integer layerId) {
		this.layerId = layerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.hole_way
	 * @return  the value of roadwork.hole_way
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getHoleWay() {
		return holeWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.hole_way
	 * @param holeWay  the value for roadwork.hole_way
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setHoleWay(String holeWay) {
		this.holeWay = holeWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.perforation_way
	 * @return  the value of roadwork.perforation_way
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getPerforationWay() {
		return perforationWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.perforation_way
	 * @param perforationWay  the value for roadwork.perforation_way
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setPerforationWay(String perforationWay) {
		this.perforationWay = perforationWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.perforation_well_section
	 * @return  the value of roadwork.perforation_well_section
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getPerforationWellSection() {
		return perforationWellSection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.perforation_well_section
	 * @param perforationWellSection  the value for roadwork.perforation_well_section
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setPerforationWellSection(String perforationWellSection) {
		this.perforationWellSection = perforationWellSection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.perforation_thick
	 * @return  the value of roadwork.perforation_thick
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getPerforationThick() {
		return perforationThick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.perforation_thick
	 * @param perforationThick  the value for roadwork.perforation_thick
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setPerforationThick(Double perforationThick) {
		this.perforationThick = perforationThick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.hole_density
	 * @return  the value of roadwork.hole_density
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getHoleDensity() {
		return holeDensity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.hole_density
	 * @param holeDensity  the value for roadwork.hole_density
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setHoleDensity(Double holeDensity) {
		this.holeDensity = holeDensity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.hole_count
	 * @return  the value of roadwork.hole_count
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getHoleCount() {
		return holeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.hole_count
	 * @param holeCount  the value for roadwork.hole_count
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setHoleCount(Integer holeCount) {
		this.holeCount = holeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.bullet_type
	 * @return  the value of roadwork.bullet_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getBulletType() {
		return bulletType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.bullet_type
	 * @param bulletType  the value for roadwork.bullet_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setBulletType(String bulletType) {
		this.bulletType = bulletType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.deep_all
	 * @return  the value of roadwork.deep_all
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getDeepAll() {
		return deepAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.deep_all
	 * @param deepAll  the value for roadwork.deep_all
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setDeepAll(Double deepAll) {
		this.deepAll = deepAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.hole_all
	 * @return  the value of roadwork.hole_all
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getHoleAll() {
		return holeAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.hole_all
	 * @param holeAll  the value for roadwork.hole_all
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setHoleAll(Integer holeAll) {
		this.holeAll = holeAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roadwork.gun_bullet_type
	 * @return  the value of roadwork.gun_bullet_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getGunBulletType() {
		return gunBulletType;
	}

	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roadwork.gun_bullet_type
	 * @param gunBulletType  the value for roadwork.gun_bullet_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setGunBulletType(String gunBulletType) {
		this.gunBulletType = gunBulletType;
	}
	
	@Override
	public String toString() {
		return "Roadwork [id=" + id + ", layerPlace=" + layerPlace + ", layerId=" + layerId + ", holeWay=" + holeWay
				+ ", perforationWay=" + perforationWay + ", perforationWellSection=" + perforationWellSection
				+ ", perforationThick=" + perforationThick + ", holeDensity=" + holeDensity + ", holeCount=" + holeCount
				+ ", bulletType=" + bulletType + ", deepAll=" + deepAll + ", holeAll=" + holeAll + ", gunBulletType="
				+ gunBulletType + "]";
	}

		
}