package com.sys.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoadworkExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public RoadworkExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceIsNull() {
			addCriterion("layer_place is null");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceIsNotNull() {
			addCriterion("layer_place is not null");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceEqualTo(String value) {
			addCriterion("layer_place =", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceNotEqualTo(String value) {
			addCriterion("layer_place <>", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceGreaterThan(String value) {
			addCriterion("layer_place >", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceGreaterThanOrEqualTo(String value) {
			addCriterion("layer_place >=", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceLessThan(String value) {
			addCriterion("layer_place <", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceLessThanOrEqualTo(String value) {
			addCriterion("layer_place <=", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceLike(String value) {
			addCriterion("layer_place like", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceNotLike(String value) {
			addCriterion("layer_place not like", value, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceIn(List<String> values) {
			addCriterion("layer_place in", values, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceNotIn(List<String> values) {
			addCriterion("layer_place not in", values, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceBetween(String value1, String value2) {
			addCriterion("layer_place between", value1, value2, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerPlaceNotBetween(String value1, String value2) {
			addCriterion("layer_place not between", value1, value2, "layerPlace");
			return (Criteria) this;
		}

		public Criteria andLayerIdIsNull() {
			addCriterion("layer_id is null");
			return (Criteria) this;
		}

		public Criteria andLayerIdIsNotNull() {
			addCriterion("layer_id is not null");
			return (Criteria) this;
		}

		public Criteria andLayerIdEqualTo(Integer value) {
			addCriterion("layer_id =", value, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdNotEqualTo(Integer value) {
			addCriterion("layer_id <>", value, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdGreaterThan(Integer value) {
			addCriterion("layer_id >", value, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("layer_id >=", value, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdLessThan(Integer value) {
			addCriterion("layer_id <", value, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdLessThanOrEqualTo(Integer value) {
			addCriterion("layer_id <=", value, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdIn(List<Integer> values) {
			addCriterion("layer_id in", values, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdNotIn(List<Integer> values) {
			addCriterion("layer_id not in", values, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdBetween(Integer value1, Integer value2) {
			addCriterion("layer_id between", value1, value2, "layerId");
			return (Criteria) this;
		}

		public Criteria andLayerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("layer_id not between", value1, value2, "layerId");
			return (Criteria) this;
		}

		public Criteria andHoleWayIsNull() {
			addCriterion("hole_way is null");
			return (Criteria) this;
		}

		public Criteria andHoleWayIsNotNull() {
			addCriterion("hole_way is not null");
			return (Criteria) this;
		}

		public Criteria andHoleWayEqualTo(String value) {
			addCriterion("hole_way =", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayNotEqualTo(String value) {
			addCriterion("hole_way <>", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayGreaterThan(String value) {
			addCriterion("hole_way >", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayGreaterThanOrEqualTo(String value) {
			addCriterion("hole_way >=", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayLessThan(String value) {
			addCriterion("hole_way <", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayLessThanOrEqualTo(String value) {
			addCriterion("hole_way <=", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayLike(String value) {
			addCriterion("hole_way like", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayNotLike(String value) {
			addCriterion("hole_way not like", value, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayIn(List<String> values) {
			addCriterion("hole_way in", values, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayNotIn(List<String> values) {
			addCriterion("hole_way not in", values, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayBetween(String value1, String value2) {
			addCriterion("hole_way between", value1, value2, "holeWay");
			return (Criteria) this;
		}

		public Criteria andHoleWayNotBetween(String value1, String value2) {
			addCriterion("hole_way not between", value1, value2, "holeWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayIsNull() {
			addCriterion("perforation_way is null");
			return (Criteria) this;
		}

		public Criteria andPerforationWayIsNotNull() {
			addCriterion("perforation_way is not null");
			return (Criteria) this;
		}

		public Criteria andPerforationWayEqualTo(String value) {
			addCriterion("perforation_way =", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayNotEqualTo(String value) {
			addCriterion("perforation_way <>", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayGreaterThan(String value) {
			addCriterion("perforation_way >", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayGreaterThanOrEqualTo(String value) {
			addCriterion("perforation_way >=", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayLessThan(String value) {
			addCriterion("perforation_way <", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayLessThanOrEqualTo(String value) {
			addCriterion("perforation_way <=", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayLike(String value) {
			addCriterion("perforation_way like", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayNotLike(String value) {
			addCriterion("perforation_way not like", value, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayIn(List<String> values) {
			addCriterion("perforation_way in", values, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayNotIn(List<String> values) {
			addCriterion("perforation_way not in", values, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayBetween(String value1, String value2) {
			addCriterion("perforation_way between", value1, value2, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWayNotBetween(String value1, String value2) {
			addCriterion("perforation_way not between", value1, value2, "perforationWay");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionIsNull() {
			addCriterion("perforation_well_section is null");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionIsNotNull() {
			addCriterion("perforation_well_section is not null");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionEqualTo(String value) {
			addCriterion("perforation_well_section =", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionNotEqualTo(String value) {
			addCriterion("perforation_well_section <>", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionGreaterThan(String value) {
			addCriterion("perforation_well_section >", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionGreaterThanOrEqualTo(String value) {
			addCriterion("perforation_well_section >=", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionLessThan(String value) {
			addCriterion("perforation_well_section <", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionLessThanOrEqualTo(String value) {
			addCriterion("perforation_well_section <=", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionLike(String value) {
			addCriterion("perforation_well_section like", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionNotLike(String value) {
			addCriterion("perforation_well_section not like", value, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionIn(List<String> values) {
			addCriterion("perforation_well_section in", values, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionNotIn(List<String> values) {
			addCriterion("perforation_well_section not in", values, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionBetween(String value1, String value2) {
			addCriterion("perforation_well_section between", value1, value2, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationWellSectionNotBetween(String value1, String value2) {
			addCriterion("perforation_well_section not between", value1, value2, "perforationWellSection");
			return (Criteria) this;
		}

		public Criteria andPerforationThickIsNull() {
			addCriterion("perforation_thick is null");
			return (Criteria) this;
		}

		public Criteria andPerforationThickIsNotNull() {
			addCriterion("perforation_thick is not null");
			return (Criteria) this;
		}

		public Criteria andPerforationThickEqualTo(Double value) {
			addCriterion("perforation_thick =", value, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickNotEqualTo(Double value) {
			addCriterion("perforation_thick <>", value, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickGreaterThan(Double value) {
			addCriterion("perforation_thick >", value, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickGreaterThanOrEqualTo(Double value) {
			addCriterion("perforation_thick >=", value, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickLessThan(Double value) {
			addCriterion("perforation_thick <", value, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickLessThanOrEqualTo(Double value) {
			addCriterion("perforation_thick <=", value, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickIn(List<Double> values) {
			addCriterion("perforation_thick in", values, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickNotIn(List<Double> values) {
			addCriterion("perforation_thick not in", values, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickBetween(Double value1, Double value2) {
			addCriterion("perforation_thick between", value1, value2, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andPerforationThickNotBetween(Double value1, Double value2) {
			addCriterion("perforation_thick not between", value1, value2, "perforationThick");
			return (Criteria) this;
		}

		public Criteria andHoleDensityIsNull() {
			addCriterion("hole_density is null");
			return (Criteria) this;
		}

		public Criteria andHoleDensityIsNotNull() {
			addCriterion("hole_density is not null");
			return (Criteria) this;
		}

		public Criteria andHoleDensityEqualTo(Double value) {
			addCriterion("hole_density =", value, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityNotEqualTo(Double value) {
			addCriterion("hole_density <>", value, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityGreaterThan(Double value) {
			addCriterion("hole_density >", value, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityGreaterThanOrEqualTo(Double value) {
			addCriterion("hole_density >=", value, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityLessThan(Double value) {
			addCriterion("hole_density <", value, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityLessThanOrEqualTo(Double value) {
			addCriterion("hole_density <=", value, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityIn(List<Double> values) {
			addCriterion("hole_density in", values, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityNotIn(List<Double> values) {
			addCriterion("hole_density not in", values, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityBetween(Double value1, Double value2) {
			addCriterion("hole_density between", value1, value2, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleDensityNotBetween(Double value1, Double value2) {
			addCriterion("hole_density not between", value1, value2, "holeDensity");
			return (Criteria) this;
		}

		public Criteria andHoleCountIsNull() {
			addCriterion("hole_count is null");
			return (Criteria) this;
		}

		public Criteria andHoleCountIsNotNull() {
			addCriterion("hole_count is not null");
			return (Criteria) this;
		}

		public Criteria andHoleCountEqualTo(Integer value) {
			addCriterion("hole_count =", value, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountNotEqualTo(Integer value) {
			addCriterion("hole_count <>", value, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountGreaterThan(Integer value) {
			addCriterion("hole_count >", value, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("hole_count >=", value, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountLessThan(Integer value) {
			addCriterion("hole_count <", value, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountLessThanOrEqualTo(Integer value) {
			addCriterion("hole_count <=", value, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountIn(List<Integer> values) {
			addCriterion("hole_count in", values, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountNotIn(List<Integer> values) {
			addCriterion("hole_count not in", values, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountBetween(Integer value1, Integer value2) {
			addCriterion("hole_count between", value1, value2, "holeCount");
			return (Criteria) this;
		}

		public Criteria andHoleCountNotBetween(Integer value1, Integer value2) {
			addCriterion("hole_count not between", value1, value2, "holeCount");
			return (Criteria) this;
		}

		public Criteria andBulletTypeIsNull() {
			addCriterion("bullet_type is null");
			return (Criteria) this;
		}

		public Criteria andBulletTypeIsNotNull() {
			addCriterion("bullet_type is not null");
			return (Criteria) this;
		}

		public Criteria andBulletTypeEqualTo(String value) {
			addCriterion("bullet_type =", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeNotEqualTo(String value) {
			addCriterion("bullet_type <>", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeGreaterThan(String value) {
			addCriterion("bullet_type >", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeGreaterThanOrEqualTo(String value) {
			addCriterion("bullet_type >=", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeLessThan(String value) {
			addCriterion("bullet_type <", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeLessThanOrEqualTo(String value) {
			addCriterion("bullet_type <=", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeLike(String value) {
			addCriterion("bullet_type like", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeNotLike(String value) {
			addCriterion("bullet_type not like", value, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeIn(List<String> values) {
			addCriterion("bullet_type in", values, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeNotIn(List<String> values) {
			addCriterion("bullet_type not in", values, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeBetween(String value1, String value2) {
			addCriterion("bullet_type between", value1, value2, "bulletType");
			return (Criteria) this;
		}

		public Criteria andBulletTypeNotBetween(String value1, String value2) {
			addCriterion("bullet_type not between", value1, value2, "bulletType");
			return (Criteria) this;
		}

		public Criteria andDeepAllIsNull() {
			addCriterion("deep_all is null");
			return (Criteria) this;
		}

		public Criteria andDeepAllIsNotNull() {
			addCriterion("deep_all is not null");
			return (Criteria) this;
		}

		public Criteria andDeepAllEqualTo(Double value) {
			addCriterion("deep_all =", value, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllNotEqualTo(Double value) {
			addCriterion("deep_all <>", value, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllGreaterThan(Double value) {
			addCriterion("deep_all >", value, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllGreaterThanOrEqualTo(Double value) {
			addCriterion("deep_all >=", value, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllLessThan(Double value) {
			addCriterion("deep_all <", value, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllLessThanOrEqualTo(Double value) {
			addCriterion("deep_all <=", value, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllIn(List<Double> values) {
			addCriterion("deep_all in", values, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllNotIn(List<Double> values) {
			addCriterion("deep_all not in", values, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllBetween(Double value1, Double value2) {
			addCriterion("deep_all between", value1, value2, "deepAll");
			return (Criteria) this;
		}

		public Criteria andDeepAllNotBetween(Double value1, Double value2) {
			addCriterion("deep_all not between", value1, value2, "deepAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllIsNull() {
			addCriterion("hole_all is null");
			return (Criteria) this;
		}

		public Criteria andHoleAllIsNotNull() {
			addCriterion("hole_all is not null");
			return (Criteria) this;
		}

		public Criteria andHoleAllEqualTo(Integer value) {
			addCriterion("hole_all =", value, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllNotEqualTo(Integer value) {
			addCriterion("hole_all <>", value, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllGreaterThan(Integer value) {
			addCriterion("hole_all >", value, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllGreaterThanOrEqualTo(Integer value) {
			addCriterion("hole_all >=", value, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllLessThan(Integer value) {
			addCriterion("hole_all <", value, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllLessThanOrEqualTo(Integer value) {
			addCriterion("hole_all <=", value, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllIn(List<Integer> values) {
			addCriterion("hole_all in", values, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllNotIn(List<Integer> values) {
			addCriterion("hole_all not in", values, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllBetween(Integer value1, Integer value2) {
			addCriterion("hole_all between", value1, value2, "holeAll");
			return (Criteria) this;
		}

		public Criteria andHoleAllNotBetween(Integer value1, Integer value2) {
			addCriterion("hole_all not between", value1, value2, "holeAll");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeIsNull() {
			addCriterion("gun_bullet_type is null");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeIsNotNull() {
			addCriterion("gun_bullet_type is not null");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeEqualTo(String value) {
			addCriterion("gun_bullet_type =", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeNotEqualTo(String value) {
			addCriterion("gun_bullet_type <>", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeGreaterThan(String value) {
			addCriterion("gun_bullet_type >", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeGreaterThanOrEqualTo(String value) {
			addCriterion("gun_bullet_type >=", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeLessThan(String value) {
			addCriterion("gun_bullet_type <", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeLessThanOrEqualTo(String value) {
			addCriterion("gun_bullet_type <=", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeLike(String value) {
			addCriterion("gun_bullet_type like", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeNotLike(String value) {
			addCriterion("gun_bullet_type not like", value, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeIn(List<String> values) {
			addCriterion("gun_bullet_type in", values, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeNotIn(List<String> values) {
			addCriterion("gun_bullet_type not in", values, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeBetween(String value1, String value2) {
			addCriterion("gun_bullet_type between", value1, value2, "gunBulletType");
			return (Criteria) this;
		}

		public Criteria andGunBulletTypeNotBetween(String value1, String value2) {
			addCriterion("gun_bullet_type not between", value1, value2, "gunBulletType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table roadwork
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table roadwork
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 04 20:49:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}