package com.sys.pojo;

import java.util.Date;

public class Roadwork {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.id
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.tid
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.captain
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private String captain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.type
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.car
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private String car;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.time
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.demo
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private String demo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roadwork.state
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.id
     *
     * @return the value of roadwork.id
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.id
     *
     * @param id the value for roadwork.id
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.tid
     *
     * @return the value of roadwork.tid
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.tid
     *
     * @param tid the value for roadwork.tid
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.captain
     *
     * @return the value of roadwork.captain
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public String getCaptain() {
        return captain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.captain
     *
     * @param captain the value for roadwork.captain
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setCaptain(String captain) {
        this.captain = captain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.type
     *
     * @return the value of roadwork.type
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.type
     *
     * @param type the value for roadwork.type
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.car
     *
     * @return the value of roadwork.car
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public String getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.car
     *
     * @param car the value for roadwork.car
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setCar(String car) {
        this.car = car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.time
     *
     * @return the value of roadwork.time
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.time
     *
     * @param time the value for roadwork.time
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.demo
     *
     * @return the value of roadwork.demo
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public String getDemo() {
        return demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.demo
     *
     * @param demo the value for roadwork.demo
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setDemo(String demo) {
        this.demo = demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roadwork.state
     *
     * @return the value of roadwork.state
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roadwork.state
     *
     * @param state the value for roadwork.state
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}