package com.sys.pojo;

import java.util.ArrayList;
import java.util.List;

public class WellInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public WellInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andWellIdIsNull() {
			addCriterion("well_id is null");
			return (Criteria) this;
		}

		public Criteria andWellIdIsNotNull() {
			addCriterion("well_id is not null");
			return (Criteria) this;
		}

		public Criteria andWellIdEqualTo(String value) {
			addCriterion("well_id =", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdNotEqualTo(String value) {
			addCriterion("well_id <>", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdGreaterThan(String value) {
			addCriterion("well_id >", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdGreaterThanOrEqualTo(String value) {
			addCriterion("well_id >=", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdLessThan(String value) {
			addCriterion("well_id <", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdLessThanOrEqualTo(String value) {
			addCriterion("well_id <=", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdLike(String value) {
			addCriterion("well_id like", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdNotLike(String value) {
			addCriterion("well_id not like", value, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdIn(List<String> values) {
			addCriterion("well_id in", values, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdNotIn(List<String> values) {
			addCriterion("well_id not in", values, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdBetween(String value1, String value2) {
			addCriterion("well_id between", value1, value2, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellIdNotBetween(String value1, String value2) {
			addCriterion("well_id not between", value1, value2, "wellId");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltIsNull() {
			addCriterion("well_deep_cmplt is null");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltIsNotNull() {
			addCriterion("well_deep_cmplt is not null");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltEqualTo(Double value) {
			addCriterion("well_deep_cmplt =", value, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltNotEqualTo(Double value) {
			addCriterion("well_deep_cmplt <>", value, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltGreaterThan(Double value) {
			addCriterion("well_deep_cmplt >", value, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltGreaterThanOrEqualTo(Double value) {
			addCriterion("well_deep_cmplt >=", value, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltLessThan(Double value) {
			addCriterion("well_deep_cmplt <", value, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltLessThanOrEqualTo(Double value) {
			addCriterion("well_deep_cmplt <=", value, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltIn(List<Double> values) {
			addCriterion("well_deep_cmplt in", values, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltNotIn(List<Double> values) {
			addCriterion("well_deep_cmplt not in", values, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltBetween(Double value1, Double value2) {
			addCriterion("well_deep_cmplt between", value1, value2, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andWellDeepCmpltNotBetween(Double value1, Double value2) {
			addCriterion("well_deep_cmplt not between", value1, value2, "wellDeepCmplt");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeIsNull() {
			addCriterion("oil_casing_type is null");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeIsNotNull() {
			addCriterion("oil_casing_type is not null");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeEqualTo(Double value) {
			addCriterion("oil_casing_type =", value, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeNotEqualTo(Double value) {
			addCriterion("oil_casing_type <>", value, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeGreaterThan(Double value) {
			addCriterion("oil_casing_type >", value, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeGreaterThanOrEqualTo(Double value) {
			addCriterion("oil_casing_type >=", value, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeLessThan(Double value) {
			addCriterion("oil_casing_type <", value, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeLessThanOrEqualTo(Double value) {
			addCriterion("oil_casing_type <=", value, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeIn(List<Double> values) {
			addCriterion("oil_casing_type in", values, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeNotIn(List<Double> values) {
			addCriterion("oil_casing_type not in", values, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeBetween(Double value1, Double value2) {
			addCriterion("oil_casing_type between", value1, value2, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingTypeNotBetween(Double value1, Double value2) {
			addCriterion("oil_casing_type not between", value1, value2, "oilCasingType");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepIsNull() {
			addCriterion("oil_casing_deep is null");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepIsNotNull() {
			addCriterion("oil_casing_deep is not null");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepEqualTo(Double value) {
			addCriterion("oil_casing_deep =", value, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepNotEqualTo(Double value) {
			addCriterion("oil_casing_deep <>", value, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepGreaterThan(Double value) {
			addCriterion("oil_casing_deep >", value, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepGreaterThanOrEqualTo(Double value) {
			addCriterion("oil_casing_deep >=", value, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepLessThan(Double value) {
			addCriterion("oil_casing_deep <", value, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepLessThanOrEqualTo(Double value) {
			addCriterion("oil_casing_deep <=", value, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepIn(List<Double> values) {
			addCriterion("oil_casing_deep in", values, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepNotIn(List<Double> values) {
			addCriterion("oil_casing_deep not in", values, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepBetween(Double value1, Double value2) {
			addCriterion("oil_casing_deep between", value1, value2, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andOilCasingDeepNotBetween(Double value1, Double value2) {
			addCriterion("oil_casing_deep not between", value1, value2, "oilCasingDeep");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerIsNull() {
			addCriterion("diameter_inner is null");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerIsNotNull() {
			addCriterion("diameter_inner is not null");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerEqualTo(String value) {
			addCriterion("diameter_inner =", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerNotEqualTo(String value) {
			addCriterion("diameter_inner <>", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerGreaterThan(String value) {
			addCriterion("diameter_inner >", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerGreaterThanOrEqualTo(String value) {
			addCriterion("diameter_inner >=", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerLessThan(String value) {
			addCriterion("diameter_inner <", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerLessThanOrEqualTo(String value) {
			addCriterion("diameter_inner <=", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerLike(String value) {
			addCriterion("diameter_inner like", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerNotLike(String value) {
			addCriterion("diameter_inner not like", value, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerIn(List<String> values) {
			addCriterion("diameter_inner in", values, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerNotIn(List<String> values) {
			addCriterion("diameter_inner not in", values, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerBetween(String value1, String value2) {
			addCriterion("diameter_inner between", value1, value2, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andDiameterInnerNotBetween(String value1, String value2) {
			addCriterion("diameter_inner not between", value1, value2, "diameterInner");
			return (Criteria) this;
		}

		public Criteria andWellThickIsNull() {
			addCriterion("well_thick is null");
			return (Criteria) this;
		}

		public Criteria andWellThickIsNotNull() {
			addCriterion("well_thick is not null");
			return (Criteria) this;
		}

		public Criteria andWellThickEqualTo(String value) {
			addCriterion("well_thick =", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickNotEqualTo(String value) {
			addCriterion("well_thick <>", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickGreaterThan(String value) {
			addCriterion("well_thick >", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickGreaterThanOrEqualTo(String value) {
			addCriterion("well_thick >=", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickLessThan(String value) {
			addCriterion("well_thick <", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickLessThanOrEqualTo(String value) {
			addCriterion("well_thick <=", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickLike(String value) {
			addCriterion("well_thick like", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickNotLike(String value) {
			addCriterion("well_thick not like", value, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickIn(List<String> values) {
			addCriterion("well_thick in", values, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickNotIn(List<String> values) {
			addCriterion("well_thick not in", values, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickBetween(String value1, String value2) {
			addCriterion("well_thick between", value1, value2, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellThickNotBetween(String value1, String value2) {
			addCriterion("well_thick not between", value1, value2, "wellThick");
			return (Criteria) this;
		}

		public Criteria andWellDeepIsNull() {
			addCriterion("well_deep is null");
			return (Criteria) this;
		}

		public Criteria andWellDeepIsNotNull() {
			addCriterion("well_deep is not null");
			return (Criteria) this;
		}

		public Criteria andWellDeepEqualTo(String value) {
			addCriterion("well_deep =", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepNotEqualTo(String value) {
			addCriterion("well_deep <>", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepGreaterThan(String value) {
			addCriterion("well_deep >", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepGreaterThanOrEqualTo(String value) {
			addCriterion("well_deep >=", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepLessThan(String value) {
			addCriterion("well_deep <", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepLessThanOrEqualTo(String value) {
			addCriterion("well_deep <=", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepLike(String value) {
			addCriterion("well_deep like", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepNotLike(String value) {
			addCriterion("well_deep not like", value, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepIn(List<String> values) {
			addCriterion("well_deep in", values, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepNotIn(List<String> values) {
			addCriterion("well_deep not in", values, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepBetween(String value1, String value2) {
			addCriterion("well_deep between", value1, value2, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andWellDeepNotBetween(String value1, String value2) {
			addCriterion("well_deep not between", value1, value2, "wellDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepIsNull() {
			addCriterion("cement_deep is null");
			return (Criteria) this;
		}

		public Criteria andCementDeepIsNotNull() {
			addCriterion("cement_deep is not null");
			return (Criteria) this;
		}

		public Criteria andCementDeepEqualTo(Double value) {
			addCriterion("cement_deep =", value, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepNotEqualTo(Double value) {
			addCriterion("cement_deep <>", value, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepGreaterThan(Double value) {
			addCriterion("cement_deep >", value, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepGreaterThanOrEqualTo(Double value) {
			addCriterion("cement_deep >=", value, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepLessThan(Double value) {
			addCriterion("cement_deep <", value, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepLessThanOrEqualTo(Double value) {
			addCriterion("cement_deep <=", value, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepIn(List<Double> values) {
			addCriterion("cement_deep in", values, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepNotIn(List<Double> values) {
			addCriterion("cement_deep not in", values, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepBetween(Double value1, Double value2) {
			addCriterion("cement_deep between", value1, value2, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andCementDeepNotBetween(Double value1, Double value2) {
			addCriterion("cement_deep not between", value1, value2, "cementDeep");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmIsNull() {
			addCriterion("atfcal_well_btm is null");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmIsNotNull() {
			addCriterion("atfcal_well_btm is not null");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmEqualTo(Double value) {
			addCriterion("atfcal_well_btm =", value, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmNotEqualTo(Double value) {
			addCriterion("atfcal_well_btm <>", value, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmGreaterThan(Double value) {
			addCriterion("atfcal_well_btm >", value, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmGreaterThanOrEqualTo(Double value) {
			addCriterion("atfcal_well_btm >=", value, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmLessThan(Double value) {
			addCriterion("atfcal_well_btm <", value, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmLessThanOrEqualTo(Double value) {
			addCriterion("atfcal_well_btm <=", value, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmIn(List<Double> values) {
			addCriterion("atfcal_well_btm in", values, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmNotIn(List<Double> values) {
			addCriterion("atfcal_well_btm not in", values, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmBetween(Double value1, Double value2) {
			addCriterion("atfcal_well_btm between", value1, value2, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andAtfcalWellBtmNotBetween(Double value1, Double value2) {
			addCriterion("atfcal_well_btm not between", value1, value2, "atfcalWellBtm");
			return (Criteria) this;
		}

		public Criteria andKillFluidIsNull() {
			addCriterion("kill_fluid is null");
			return (Criteria) this;
		}

		public Criteria andKillFluidIsNotNull() {
			addCriterion("kill_fluid is not null");
			return (Criteria) this;
		}

		public Criteria andKillFluidEqualTo(String value) {
			addCriterion("kill_fluid =", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidNotEqualTo(String value) {
			addCriterion("kill_fluid <>", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidGreaterThan(String value) {
			addCriterion("kill_fluid >", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidGreaterThanOrEqualTo(String value) {
			addCriterion("kill_fluid >=", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidLessThan(String value) {
			addCriterion("kill_fluid <", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidLessThanOrEqualTo(String value) {
			addCriterion("kill_fluid <=", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidLike(String value) {
			addCriterion("kill_fluid like", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidNotLike(String value) {
			addCriterion("kill_fluid not like", value, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidIn(List<String> values) {
			addCriterion("kill_fluid in", values, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidNotIn(List<String> values) {
			addCriterion("kill_fluid not in", values, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidBetween(String value1, String value2) {
			addCriterion("kill_fluid between", value1, value2, "killFluid");
			return (Criteria) this;
		}

		public Criteria andKillFluidNotBetween(String value1, String value2) {
			addCriterion("kill_fluid not between", value1, value2, "killFluid");
			return (Criteria) this;
		}

		public Criteria andDensityIsNull() {
			addCriterion("density is null");
			return (Criteria) this;
		}

		public Criteria andDensityIsNotNull() {
			addCriterion("density is not null");
			return (Criteria) this;
		}

		public Criteria andDensityEqualTo(Double value) {
			addCriterion("density =", value, "density");
			return (Criteria) this;
		}

		public Criteria andDensityNotEqualTo(Double value) {
			addCriterion("density <>", value, "density");
			return (Criteria) this;
		}

		public Criteria andDensityGreaterThan(Double value) {
			addCriterion("density >", value, "density");
			return (Criteria) this;
		}

		public Criteria andDensityGreaterThanOrEqualTo(Double value) {
			addCriterion("density >=", value, "density");
			return (Criteria) this;
		}

		public Criteria andDensityLessThan(Double value) {
			addCriterion("density <", value, "density");
			return (Criteria) this;
		}

		public Criteria andDensityLessThanOrEqualTo(Double value) {
			addCriterion("density <=", value, "density");
			return (Criteria) this;
		}

		public Criteria andDensityIn(List<Double> values) {
			addCriterion("density in", values, "density");
			return (Criteria) this;
		}

		public Criteria andDensityNotIn(List<Double> values) {
			addCriterion("density not in", values, "density");
			return (Criteria) this;
		}

		public Criteria andDensityBetween(Double value1, Double value2) {
			addCriterion("density between", value1, value2, "density");
			return (Criteria) this;
		}

		public Criteria andDensityNotBetween(Double value1, Double value2) {
			addCriterion("density not between", value1, value2, "density");
			return (Criteria) this;
		}

		public Criteria andViscosityIsNull() {
			addCriterion("viscosity is null");
			return (Criteria) this;
		}

		public Criteria andViscosityIsNotNull() {
			addCriterion("viscosity is not null");
			return (Criteria) this;
		}

		public Criteria andViscosityEqualTo(Double value) {
			addCriterion("viscosity =", value, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityNotEqualTo(Double value) {
			addCriterion("viscosity <>", value, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityGreaterThan(Double value) {
			addCriterion("viscosity >", value, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityGreaterThanOrEqualTo(Double value) {
			addCriterion("viscosity >=", value, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityLessThan(Double value) {
			addCriterion("viscosity <", value, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityLessThanOrEqualTo(Double value) {
			addCriterion("viscosity <=", value, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityIn(List<Double> values) {
			addCriterion("viscosity in", values, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityNotIn(List<Double> values) {
			addCriterion("viscosity not in", values, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityBetween(Double value1, Double value2) {
			addCriterion("viscosity between", value1, value2, "viscosity");
			return (Criteria) this;
		}

		public Criteria andViscosityNotBetween(Double value1, Double value2) {
			addCriterion("viscosity not between", value1, value2, "viscosity");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table well_info
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table well_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 14 20:26:56 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}