package com.sys.pojo;

public class WellInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.well_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String wellId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.well_deep_cmplt
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double wellDeepCmplt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.oil_casing_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double oilCasingType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.oil_casing_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double oilCasingDeep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.diameter_inner
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String diameterInner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.well_thick
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String wellThick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.well_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String wellDeep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.cement_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double cementDeep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.atfcal_well_btm
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double atfcalWellBtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.kill_fluid
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private String killFluid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.density
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double density;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column well_info.viscosity
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	private Double viscosity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.id
	 * @return  the value of well_info.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.id
	 * @param id  the value for well_info.id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.well_id
	 * @return  the value of well_info.well_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getWellId() {
		return wellId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.well_id
	 * @param wellId  the value for well_info.well_id
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setWellId(String wellId) {
		this.wellId = wellId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.well_deep_cmplt
	 * @return  the value of well_info.well_deep_cmplt
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getWellDeepCmplt() {
		return wellDeepCmplt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.well_deep_cmplt
	 * @param wellDeepCmplt  the value for well_info.well_deep_cmplt
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setWellDeepCmplt(Double wellDeepCmplt) {
		this.wellDeepCmplt = wellDeepCmplt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.oil_casing_type
	 * @return  the value of well_info.oil_casing_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getOilCasingType() {
		return oilCasingType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.oil_casing_type
	 * @param oilCasingType  the value for well_info.oil_casing_type
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setOilCasingType(Double oilCasingType) {
		this.oilCasingType = oilCasingType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.oil_casing_deep
	 * @return  the value of well_info.oil_casing_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getOilCasingDeep() {
		return oilCasingDeep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.oil_casing_deep
	 * @param oilCasingDeep  the value for well_info.oil_casing_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setOilCasingDeep(Double oilCasingDeep) {
		this.oilCasingDeep = oilCasingDeep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.diameter_inner
	 * @return  the value of well_info.diameter_inner
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getDiameterInner() {
		return diameterInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.diameter_inner
	 * @param diameterInner  the value for well_info.diameter_inner
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setDiameterInner(String diameterInner) {
		this.diameterInner = diameterInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.well_thick
	 * @return  the value of well_info.well_thick
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getWellThick() {
		return wellThick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.well_thick
	 * @param wellThick  the value for well_info.well_thick
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setWellThick(String wellThick) {
		this.wellThick = wellThick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.well_deep
	 * @return  the value of well_info.well_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getWellDeep() {
		return wellDeep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.well_deep
	 * @param wellDeep  the value for well_info.well_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setWellDeep(String wellDeep) {
		this.wellDeep = wellDeep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.cement_deep
	 * @return  the value of well_info.cement_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getCementDeep() {
		return cementDeep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.cement_deep
	 * @param cementDeep  the value for well_info.cement_deep
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setCementDeep(Double cementDeep) {
		this.cementDeep = cementDeep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.atfcal_well_btm
	 * @return  the value of well_info.atfcal_well_btm
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getAtfcalWellBtm() {
		return atfcalWellBtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.atfcal_well_btm
	 * @param atfcalWellBtm  the value for well_info.atfcal_well_btm
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setAtfcalWellBtm(Double atfcalWellBtm) {
		this.atfcalWellBtm = atfcalWellBtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.kill_fluid
	 * @return  the value of well_info.kill_fluid
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public String getKillFluid() {
		return killFluid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.kill_fluid
	 * @param killFluid  the value for well_info.kill_fluid
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setKillFluid(String killFluid) {
		this.killFluid = killFluid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.density
	 * @return  the value of well_info.density
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getDensity() {
		return density;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.density
	 * @param density  the value for well_info.density
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setDensity(Double density) {
		this.density = density;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column well_info.viscosity
	 * @return  the value of well_info.viscosity
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public Double getViscosity() {
		return viscosity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column well_info.viscosity
	 * @param viscosity  the value for well_info.viscosity
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	public void setViscosity(Double viscosity) {
		this.viscosity = viscosity;
	}
}