package com.crx.pojo;

public class Cost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.name
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.type
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.number
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.id
     *
     * @return the value of cost.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.id
     *
     * @param id the value for cost.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.name
     *
     * @return the value of cost.name
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.name
     *
     * @param name the value for cost.name
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.type
     *
     * @return the value of cost.type
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.type
     *
     * @param type the value for cost.type
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.number
     *
     * @return the value of cost.number
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.number
     *
     * @param number the value for cost.number
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.time
     *
     * @return the value of cost.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.time
     *
     * @param time the value for cost.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setTime(String time) {
        this.time = time;
    }
}