package com.crx.pojo;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.horizon
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String horizon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.h_id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.bottom
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Double bottom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.top
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Double top;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.address
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.density
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer density;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.type
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.horizon
     *
     * @return the value of notice.horizon
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getHorizon() {
        return horizon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.horizon
     *
     * @param horizon the value for notice.horizon
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setHorizon(String horizon) {
        this.horizon = horizon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.h_id
     *
     * @return the value of notice.h_id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.h_id
     *
     * @param hId the value for notice.h_id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.bottom
     *
     * @return the value of notice.bottom
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Double getBottom() {
        return bottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.bottom
     *
     * @param bottom the value for notice.bottom
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setBottom(Double bottom) {
        this.bottom = bottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.top
     *
     * @return the value of notice.top
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Double getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.top
     *
     * @param top the value for notice.top
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setTop(Double top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.time
     *
     * @return the value of notice.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.time
     *
     * @param time the value for notice.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.address
     *
     * @return the value of notice.address
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.address
     *
     * @param address the value for notice.address
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.density
     *
     * @return the value of notice.density
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.density
     *
     * @param density the value for notice.density
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setDensity(Integer density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.type
     *
     * @return the value of notice.type
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.type
     *
     * @param type the value for notice.type
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}