package com.crx.pojo;

public class Perforation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.tid
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.cable_perforation
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Double cablePerforation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.oil_delivery
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Double oilDelivery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.bridge_plug
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer bridgePlug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.ashes
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer ashes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.tubing_cutting
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer tubingCutting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.punching
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer punching;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perforation.engineering
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer engineering;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.id
     *
     * @return the value of perforation.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.id
     *
     * @param id the value for perforation.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.tid
     *
     * @return the value of perforation.tid
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.tid
     *
     * @param tid the value for perforation.tid
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.cable_perforation
     *
     * @return the value of perforation.cable_perforation
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Double getCablePerforation() {
        return cablePerforation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.cable_perforation
     *
     * @param cablePerforation the value for perforation.cable_perforation
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setCablePerforation(Double cablePerforation) {
        this.cablePerforation = cablePerforation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.oil_delivery
     *
     * @return the value of perforation.oil_delivery
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Double getOilDelivery() {
        return oilDelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.oil_delivery
     *
     * @param oilDelivery the value for perforation.oil_delivery
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setOilDelivery(Double oilDelivery) {
        this.oilDelivery = oilDelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.bridge_plug
     *
     * @return the value of perforation.bridge_plug
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getBridgePlug() {
        return bridgePlug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.bridge_plug
     *
     * @param bridgePlug the value for perforation.bridge_plug
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setBridgePlug(Integer bridgePlug) {
        this.bridgePlug = bridgePlug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.ashes
     *
     * @return the value of perforation.ashes
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getAshes() {
        return ashes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.ashes
     *
     * @param ashes the value for perforation.ashes
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setAshes(Integer ashes) {
        this.ashes = ashes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.tubing_cutting
     *
     * @return the value of perforation.tubing_cutting
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getTubingCutting() {
        return tubingCutting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.tubing_cutting
     *
     * @param tubingCutting the value for perforation.tubing_cutting
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setTubingCutting(Integer tubingCutting) {
        this.tubingCutting = tubingCutting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.punching
     *
     * @return the value of perforation.punching
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getPunching() {
        return punching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.punching
     *
     * @param punching the value for perforation.punching
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setPunching(Integer punching) {
        this.punching = punching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perforation.engineering
     *
     * @return the value of perforation.engineering
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getEngineering() {
        return engineering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perforation.engineering
     *
     * @param engineering the value for perforation.engineering
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setEngineering(Integer engineering) {
        this.engineering = engineering;
    }
}