package com.crx.pojo;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_name
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_url
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    private String permissionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.available
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    private Integer available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_name
     *
     * @return the value of permission.permission_name
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_name
     *
     * @param permissionName the value for permission.permission_name
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_url
     *
     * @return the value of permission.permission_url
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_url
     *
     * @param permissionUrl the value for permission.permission_url
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.available
     *
     * @return the value of permission.available
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.available
     *
     * @param available the value for permission.available
     *
     * @mbg.generated Sun Jul 28 18:36:37 CST 2019
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }
}