package com.crx.pojo;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.price
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.number
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.price
     *
     * @return the value of stock.price
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.price
     *
     * @param price the value for stock.price
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.number
     *
     * @return the value of stock.number
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.number
     *
     * @param number the value for stock.number
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.time
     *
     * @return the value of stock.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.time
     *
     * @param time the value for stock.time
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setTime(String time) {
        this.time = time;
    }
}