package com.crx.pojo;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.tid
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.well_text
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer wellText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.fracturing
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer fracturing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.log
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer log;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.depth_correction
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    private Integer depthCorrection;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.tid
     *
     * @return the value of test.tid
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.tid
     *
     * @param tid the value for test.tid
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.well_text
     *
     * @return the value of test.well_text
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getWellText() {
        return wellText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.well_text
     *
     * @param wellText the value for test.well_text
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setWellText(Integer wellText) {
        this.wellText = wellText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.fracturing
     *
     * @return the value of test.fracturing
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getFracturing() {
        return fracturing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.fracturing
     *
     * @param fracturing the value for test.fracturing
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setFracturing(Integer fracturing) {
        this.fracturing = fracturing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.log
     *
     * @return the value of test.log
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.log
     *
     * @param log the value for test.log
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setLog(Integer log) {
        this.log = log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.depth_correction
     *
     * @return the value of test.depth_correction
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public Integer getDepthCorrection() {
        return depthCorrection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.depth_correction
     *
     * @param depthCorrection the value for test.depth_correction
     *
     * @mbg.generated Tue Jul 30 21:22:56 CST 2019
     */
    public void setDepthCorrection(Integer depthCorrection) {
        this.depthCorrection = depthCorrection;
    }
}