package com.sys.mapper;

import com.sys.pojo.File;
import com.sys.pojo.FileExample;
import com.sys.pojo.Roadwork;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    long countByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int deleteByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    List<File> selectByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    File selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int updateByExample(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Aug 05 22:09:04 CST 2019
     */
    int updateByPrimaryKey(File record);
    
    /**
            * 分页查询
     * @param map
     * @return
*/
List<File> selectByPage(Map<String, Long> map);

	/**
	   * 查询总数
	 * @return
	 */
	
	Long selectCount();
	    
}