package com.sys.mapper;

import com.sys.pojo.PerforationNotice;
import com.sys.pojo.PerforationNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PerforationNoticeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	long countByExample(PerforationNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int deleteByExample(PerforationNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int insert(PerforationNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int insertSelective(PerforationNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	List<PerforationNotice> selectByExample(PerforationNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	PerforationNotice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int updateByExampleSelective(@Param("record") PerforationNotice record,
			@Param("example") PerforationNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int updateByExample(@Param("record") PerforationNotice record, @Param("example") PerforationNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int updateByPrimaryKeySelective(PerforationNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perforation_notice
	 * @mbg.generated  Wed Aug 14 20:27:46 CST 2019
	 */
	int updateByPrimaryKey(PerforationNotice record);
}