package com.sys.mapper;

import com.sys.pojo.AdminUser;
import com.sys.pojo.Roadwork;
import com.sys.pojo.RoadworkExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RoadworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    long countByExample(RoadworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int deleteByExample(RoadworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int insert(Roadwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int insertSelective(Roadwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    List<Roadwork> selectByExample(RoadworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    Roadwork selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Roadwork record, @Param("example") RoadworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int updateByExample(@Param("record") Roadwork record, @Param("example") RoadworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int updateByPrimaryKeySelective(Roadwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roadwork
     *
     * @mbg.generated Sun Aug 04 20:49:51 CST 2019
     */
    int updateByPrimaryKey(Roadwork record);
    
    /**
            * 分页查询
     * @param map
     * @return
     */
    List<Roadwork> selectByPage(Map<String, Long> map);
    
    /**
            * 查询总数
     * @return
     */
    
    Long selectCount();
}